# Generated by Django 2.0.4 on 2018-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('users', '0004_auto_20180412_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userartists',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='artist_id',
            field=models.ManyToManyField(to='artists.Artists'),
        ),
        migrations.DeleteModel(
            name='UserArtists',
        ),
    ]
