# Generated by Django 2.0.4 on 2018-04-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180413_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trackartist',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
