# Generated by Django 2.0.4 on 2018-04-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180414_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='track_artists',
            field=models.ManyToManyField(related_name='track_artists', through='users.TrackArtist', to='artists.Artists'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_events',
            field=models.ManyToManyField(related_name='user_events', through='users.Plan', to='events.Events'),
        ),
    ]
