# Generated by Django 2.0.4 on 2018-04-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20180414_1235'),
        ('users', '0013_auto_20180414_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=64)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artists')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='trackartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='trackartist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='track_artists',
        ),
        migrations.DeleteModel(
            name='TrackArtist',
        ),
        migrations.AddField(
            model_name='followartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_artists',
            field=models.ManyToManyField(related_name='follow_artists', through='users.FollowArtist', to='artists.Artists'),
        ),
    ]
