# Generated by Django 2.0.4 on 2018-04-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180414_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='status',
        ),
    ]
