# Generated by Django 2.0.4 on 2018-04-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_plan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow_artists',
            new_name='following_artists',
        ),
    ]
