# Generated by Django 2.0.4 on 2018-04-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={},
        ),
    ]
