# Generated by Django 2.0.4 on 2018-04-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180414_1155'),
        ('artists', '0002_auto_20180414_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artistname', models.CharField(blank=True, db_column='artistName', max_length=255, null=True)),
                ('attractionid', models.CharField(blank=True, db_column='attractionId', max_length=255, null=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artists')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artists',
            name='artist_events',
            field=models.ManyToManyField(through='artists.ArtistEvents', to='events.Events'),
        ),
    ]
