# Generated by Django 2.0.4 on 2018-04-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20180414_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistevents',
            name='artist',
            field=models.ForeignKey(db_column='artistId', on_delete=django.db.models.deletion.CASCADE, to='artists.Artists'),
        ),
        migrations.AlterField(
            model_name='artistevents',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
