# Generated by Django 2.0.4 on 2018-04-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180414_1155'),
        ('artists', '0005_auto_20180414_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistEvents',
            new_name='ArtistEvent',
        ),
    ]
