# Generated by Django 2.0.4 on 2018-04-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20180414_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artist_events',
            new_name='events',
        ),
    ]
