# Generated by Django 2.0.4 on 2018-04-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20180416_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ['-popularity']},
        ),
    ]
