# Generated by Django 2.0.4 on 2018-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20180412_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='event_image_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='event_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='event_start_local_date',
            field=models.DateField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='event_start_local_time',
            field=models.TimeField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='venue_city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='venue_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='venue_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='venue_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='venue_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='venue_street',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
