# Generated by Django 2.0.4 on 2018-04-16 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180414_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.CharField(db_column='venueId', max_length=255, primary_key=True, serialize=False)),
                ('venuename', models.CharField(blank=True, db_column='venueName', max_length=1024, null=True)),
                ('venuecity', models.CharField(blank=True, db_column='venueCity', max_length=255, null=True)),
                ('venuestatecode', models.CharField(blank=True, db_column='venueStateCode', max_length=50, null=True)),
                ('venuecountrycode', models.CharField(blank=True, db_column='venueCountryCode', max_length=50, null=True)),
                ('venuestreet', models.CharField(blank=True, db_column='venueStreet', max_length=1024, null=True)),
                ('venuezipcode', models.CharField(blank=True, db_column='venueZipCode', max_length=255, null=True)),
                ('venuelatitude', models.FloatField(blank=True, db_column='venueLatitude', null=True)),
                ('venuelongitude', models.FloatField(blank=True, db_column='venueLongitude', null=True)),
                ('venueurl', models.CharField(blank=True, db_column='venueUrl', max_length=1024, null=True)),
                ('venuetimezone', models.CharField(blank=True, db_column='venueTimezone', max_length=255, null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='venueid',
            field=models.ForeignKey(db_column='venueId', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue'),
        ),
    ]
