# Generated by Django 2.0.4 on 2018-04-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180416_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
    ]
