# Generated by Django 2.0.4 on 2018-04-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20180414_2110'),
        ('users', '0017_auto_20180416_1016'),
        ('events', '0005_remove_venue_createdat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
