# Generated by Django 2.0.4 on 2018-04-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180416_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venueid',
            new_name='venue',
        ),
    ]
